name: Lint and Format Check

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-and-format:
    name: Check Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v7
        with:
          python-version-file: ".python-version"

      - run: uv sync --all-groups --frozen

      - name: Check Lint
        run: uv run ruff check .

      - name: Check Formatting
        run: uv run ruff format --check .
